default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  encoding: utf8
  ctype: en_US.utf8
  collation: en_US.utf8
  template: template0

development:
  <<: *default
  database: isl-fantasy_development
  username: isl-fantasy-user
  password: isl-fantasy-user

test:
  <<: *default
  database: isl-fantasy_test
  username: isl-fantasy-user
  password: isl-fantasy-user