# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6e5a8f28954052994249d3ea0b8ba6af78eb14da0126636c98d8a8f1dddd1d95dfa3395a82eaec0f2f9ae59d77f93ef9f528421943ade4b3fbe852e21bc46bd

test:
  secret_key_base: 5fb140f4e2c36d1338cab94b0f5d6ce0e8eebf2ea2abc251f02c843719a81746f553a586a28a1b72e786f01001a80af860ca1ff3e407cdd6306ce1d84f687f1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
